(require 'rtags)
(rtags-enable-standard-keybindings c-mode-base-map)
(setq rtags-completions-enabled t)
(add-hook 'c-mode-common-hook
          (lambda ()
	    (autoload 'cmake-project-mode "cmake-project")
	    (setq flymake-mode nil)
              ))
(add-hook 'c++-mode-hook
          (lambda ()
	    (require 'auto-complete)
	    (require 'auto-complete-config)
	    (ac-config-default)
	    (require 'popup)
	    (require 'rtags-ac)
	    (setq ac-sources '(ac-source-rtags))
    	    (require 'yasnippet)
	    (yas-minor-mode)
	    (local-set-key (kbd "M-/") 'auto-complete)
	    ))
;; (add-hook 'c++-mode-hook
;;           (lambda ()
;; 	    (require 'company-rtags)
;; 	    (setq company-backends '(company-rtags))
;; 	    (company-mode)
;; 	    (rtags-diagnostics)
;; 	    (local-unset-key (kbd "M-/"))
;; 	    (local-set-key (kbd "M-/") 'company-complete)
;; ))

(provide 'cpp-octi-new)
